### ISSUE TITLE
Paper or code to prefer this dataset

### ISSUE THREAD

**Issue by haiton266** [phiyodr/dacl10k-toolkit#6]
I read some information on https://dacl.ai/workshop.html that the competition has 1 workshop occurring in Jan 2024. But now, I still find nothing about source code or paper. Do you have any information? I want to refer for my research, thank you!

**Comment by phiyodr** [comment]
Hi, thanks for your interest! Attended the link to our publications: https://github.com/phiyodr/dacl10k-toolkit/blob/master/README.md#please-cite

Please look at [dacl-challenge: Semantic Segmentation during Visual Bridge Inspections](https://openaccess.thecvf.com/content/WACV2024W/DACL/html/Flotzinger_Dacl-Challenge_Semantic_Segmentation_During_Visual_Bridge_Inspections_WACVW_2024_paper.html) for source code references of the competition winners. I hope this helps!
